name: Cypress Parallel Execution
 
on:
  push:
    branches: [main, test]
  workflow_dispatch:
  
 
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
     
      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
           name: code-coverage-report
           path: cypress/downloads/reports/code-coverage.html

      # Step 7: Archive Screenshot 
      - name: Archive Cypress screenshots
        uses: actions/upload-artifact@v4
        with:
           name: checkout_screenshot
           path: cypress/screenshots/

      # Step 8: Rename report file to index.html for GitHub Pages
      - name: Prepare report file for Github Pages
        run: mv cypress/downloads/reports/code-coverage.html cypress/downloads/reports/index.html

      # Step 9: Upload report to GitHub Pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: cypress/downloads/reports/

  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}

    steps:
      - name: Create Matrix
        id: prepare
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 3
      - name: Print result
        run: echo '${{ steps.prepare.outputs.matrix }}'
  
  test-split:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Print Github Variables
        run: npx @bahmutov/print-env GITHUB

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: cypress-split     

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
        
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
